export enum OrderStatus {
  COMPLETED = 'COMPLETED',
  DISPATCHED = 'DISPATCHED',
  IN_PROGRESS = 'IN_PROGRESS',
  NEW = 'NEW',
  RATED = 'RATED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  SEEN = 'SEEN',
}
